#!/bin/bash

## Usage: format <device>
## This file formats a given device and then creates the file "check_stamp.nat" so that verify
## correctly says that this device has been formatted for backups

if [[ "$(whoami)" != "root" ]]; then
	echo "Must be run as root. Try 'sudo !!'"
	exit 0
fi

main() {
	if [ $# -eq 0 ]; then
		echo "Usage: format <device>"
		exit 0
	fi

	printf "Are you sure you'd like to format $1 [y/N]? "
	read choice
	if [[ ! "$choice" == "y" && ! "$choice" == "Y" ]]; then
		echo "Quitting."
		exit 0
	fi

	echo "Formatting $1."
	mkfs.xfs -f $1

	tmpdir=`mktemp -d`
	mount $1 $tmpdir

	touch $tmpdir/check_stamp.nat
	umount $1
	rmdir $tmpdir
}

main "$@"
