#!/bin/bash

user=`whoami`
if [[ "$user" != "root" ]]; then
	echo "Must be run as root."
	exit
fi



cd src
make
cd ..

chown root:root .

cp src/cback /usr/bin/cback
cp bash_scripts/e_format /usr/bin/e_format
cp bash_scripts/e_verify /usr/bin/e_verify
cp bash_scripts/eback /usr/bin/eback

chmod 755 /usr/bin/cback
chmod 755 /usr/bin/e_format
chmod 755 /usr/bin/e_verify
chmod 755 /usr/bin/eback

mkdir /etc/eback/
